language: node_js
node_js:
  - '10'

notifications:
  email: false

script:
  - npm run lint
  - npm run build
  - npm run test:ci

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
